# Generated by Django 5.1.1 on 2024-10-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
