# Generated by Django 5.1.1 on 2024-10-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_superhero_description_alter_superhero_image'),
        ('hero', '0003_hero_author'),
    ]

    operations = [
    ]
